### ISSUE TITLE
Account name/menu is almost invisible

### ISSUE THREAD

**Issue by GauthierPLM** [RaitaroH/Qwant-DeepDark#1]
The account menu (available when logged in, top left corner) is really had to read with dark theme:

- Either the text is invisible (with Arc Dark theme for example),
- Either the font colour is almost the same as background (Vertex dark)

I hope you'll be able to fix that, for the rest, the theme looks nice.

**Comment by RaitaroH** [comment]
I haven't loged in myself. I did this for some guy on reddit :P

I will take a look.

**Comment by RaitaroH** [comment]
Fixed.

**Comment by GauthierPLM** [comment]
I am the guy from Reddit ;)
Thanks for the fix!
