### ISSUE TITLE
Black and White theme makes "Share Qwant" button unreadable

### ISSUE THREAD

**Issue by GauthierPLM** [RaitaroH/Qwant-DeepDark#2]
The button has white background with white text, which make it only white and unreadable.

**Comment by RaitaroH** [comment]
Ah, where is the share button btw.

**Comment by GauthierPLM** [comment]
![This in a screenshot of the page, on French version.](https://user-images.githubusercontent.com/2579741/36302421-c23aa7fe-134b-11e8-991f-88055a4a800a.png) I suspect that the button is not available for other languages.

**Comment by RaitaroH** [comment]
A... That is install button man.

**Comment by RaitaroH** [comment]
@GauthierPLM Please inform me of any more bugs.

**Comment by GauthierPLM** [comment]
The button is also "Share Qwant" in French ;)
Anyway, thanks for solving the problems!

**Comment by RaitaroH** [comment]
@GauthierPLM No problem.
