### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by qazip** [RaitaroH/Qwant-DeepDark#4]
It doesn't work on my end. I am using it with stylus and the page does not change color (some stuff like the logo does change slightly).

**Comment by qazip** [comment]
Installing it from https://userstyles.org/ made it work. The version there and the version in openstyles are probably different?

**Comment by RaitaroH** [comment]
Well I dont have the time to work on this theme. Also I don't use it and I never had. I made this as a request for somebody. Please consider this theme as dead.

If you want to contribute make a pull request.
